# Generated by Django 4.2.1 on 2023-05-21 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('CONSULTA_GENERAL', 'Consulta general'), ('VACUNACION_A', 'Vacunacion A'), ('VACUNACION_B', 'Vacunacion B'), ('DESPARACITACION', 'Desparacitacion'), ('CASTRACION', 'Castracion'), ('URGENCIA', 'Urgencia')], max_length=16)),
                ('request_date', models.DateField()),
                ('request_timeslot', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], max_length=16)),
                ('actual_datetime', models.DateTimeField(null=True)),
                ('suggestion_datetime', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('APR', 'Approved'), ('REJ', 'Rejected'), ('CAN', 'Canceled'), ('COM', 'Completed')], default='PEN', max_length=16)),
                ('observations', models.TextField()),
                ('days_to_booster', models.IntegerField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('user', models.ForeignKey(on_delete=models.Model, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
