# Generated by Django 4.2.1 on 2023-07-06 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('VACUNA', 'Vacuna'), ('PESO', 'Peso')], max_length=16)),
                ('vaccine', models.CharField(max_length=16, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
    ]
