# Generated by Django 4.2.1 on 2023-05-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('CONSULTA_GENERAL', 'Consulta general'), ('VACUNACION_A', 'Vacunacion A'), ('VACUNACION_B', 'Vacunacion B'), ('DESPARASITACION', 'Desparasitacion'), ('CASTRACION', 'Castracion'), ('URGENCIA', 'Urgencia')], max_length=16),
        ),
    ]
