from ohmydog.utils.choices import choice, make_choices
from django.utils.translation import gettext_lazy as _


TIMESLOT_MORNING = 'MANANA'
TIMESLOT_AFTERNOON = 'TARDE'

TIMESLOTS = {
    TIMESLOT_MORNING: choice(TIMESLOT_MORNING, _('Mañana')),
    TIMESLOT_AFTERNOON: choice(TIMESLOT_AFTERNOON, _('Tarde')),
}

TIMESLOT_CHOICES = make_choices(TIMESLOTS)


REASON_CONSULTATION = 'CONSULTA_GENERAL'
REASON_VACCINATION_A = 'VACUNACION_A'
REASON_VACCINATION_B = 'VACUNACION_B'
REASON_DEWORMING = 'DESPARASITACION'
REASON_CASTRATION = 'CASTRACION'
REASON_URGENCY = 'URGENCIA'

VACCINATION_REASONS = [REASON_VACCINATION_A, REASON_VACCINATION_B]

REASONS = {
    REASON_CONSULTATION: choice(REASON_CONSULTATION, _('Consulta general')),
    REASON_VACCINATION_A: choice(REASON_VACCINATION_A, _('Vacunacion A')),
    REASON_VACCINATION_B: choice(REASON_VACCINATION_B, _('Vacunacion B')),
    REASON_DEWORMING: choice(REASON_DEWORMING, _('Desparasitacion')),
    REASON_CASTRATION: choice(REASON_CASTRATION, _('Castracion')),
    REASON_URGENCY: choice(REASON_URGENCY, _('Urgencia')),
}

REASON_CHOICES = make_choices(REASONS)


STATUS_PENDING = 'PEN'
STATUS_ACCEPTED = 'APR'
STATUS_REJECTED = 'REJ'
STATUS_CANCELED = 'CAN'
STATUS_COMPLETED = 'COM'

STATUSES = {
    STATUS_PENDING: choice(STATUS_PENDING, _('Pendiente')), 
    STATUS_ACCEPTED: choice(STATUS_ACCEPTED, _('Aceptado')),
    STATUS_REJECTED: choice(STATUS_REJECTED, _('Rechazado')),
    STATUS_CANCELED: choice(STATUS_CANCELED, _('Cancelado')),
    STATUS_COMPLETED: choice(STATUS_COMPLETED, _('Completado')),
}

STATUS_CHOICES = make_choices(STATUSES)
