# Generated by Django 4.2.1 on 2023-07-10 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSitterAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PUB', 'Publicado'), ('COM', 'Completado'), ('CAN', 'Cancelado'), ('PAU', 'Pausado')], default='PUB', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pause_start_date', models.DateField(null=True)),
                ('pause_end_date', models.DateField(null=True)),
                ('sitter_first_name', models.CharField(max_length=150)),
                ('sitter_last_name', models.CharField(max_length=150)),
                ('sitter_email', models.EmailField(max_length=254)),
                ('sitter_phone_number', models.CharField(max_length=32)),
                ('service_type', models.CharField(choices=[('CUIDADOR', 'Cuidador'), ('PASEADOR', 'Paseador')], max_length=16)),
                ('service_area', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
