# Generated by Django 4.2.1 on 2023-07-12 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSearchAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PUB', 'Publicado'), ('COM', 'Completado'), ('CAN', 'Cancelado'), ('PAU', 'Pausado')], default='PUB', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pause_start_date', models.DateField(null=True)),
                ('pause_end_date', models.DateField(null=True)),
                ('pet_name', models.CharField(max_length=32)),
                ('pet_age', models.PositiveIntegerField()),
                ('pet_gender', models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=16)),
                ('pet_breed', models.CharField(max_length=32)),
                ('pet_size', models.CharField(choices=[('PEQUENO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=16)),
                ('pet_color', models.CharField(max_length=32)),
                ('last_seen_area', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
