# Generated by Django 4.2.1 on 2023-07-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsearches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsearchad',
            name='pet_photo',
            field=models.ImageField(null=True, upload_to='petsearches'),
        ),
    ]
